import {
  ChevronLeft,
  Camera,
  User,
  Mail,
  Lock,
  Calendar,
  Globe,
  Building2,
  GraduationCap,
  School,
  Moon,
  Sun,
  Pencil,
  Phone,
} from "lucide-react";

export const inputFields = [
  {
    label: "Name",
    icon: User,
    value: "",
    type: "text",
    name: "name",
  },

  {
    label: "Date of Birth",
    icon: Calendar,
    value: "",
    type: "date",
    name: "age",
  },

  {
    label: "Phone No.",
    icon: Phone,
    value: "",
    type: "tel",
    name: "phoneNumber",
    placeholder: "Enter your phone No.",
  },
  {
    label: "Region",
    icon: Globe,
    value: "",
    type: "text",
    name: "region",
    placeholder: "Enter you region",
  },
  {
    label: "City",
    icon: Building2,
    value: "",
    type: "text",
    placeholder: "Enter your city",
    name: "city",
  },
  {
    label: "Grade",
    icon: GraduationCap,
    value: "",
    type: "number",
    placeholder: "Enter your grade",
    min: 1,
    max: 12,
    name: "grade",
  },
  {
    label: "School",
    icon: School,
    value: "",
    type: "text",
    placeholder: "Enter your school name",
    name: "school",
  },
];
